name: 'Security Audit'
description: 'Run security audit and count vulnerabilities'
inputs:
  fail-on-critical:
    description: 'Fail on critical severity vulnerabilities'
    required: false
    default: 'true'
  fail-on-high:
    description: 'Fail on high severity vulnerabilities'
    required: false
    default: 'true'
  upload-artifacts:
    description: 'Upload audit results as artifacts'
    required: false
    default: 'true'

outputs:
  critical-count:
    description: 'Number of critical vulnerabilities'
    value: ${{ steps.audit.outputs.critical-count }}
  high-count:
    description: 'Number of high severity vulnerabilities'
    value: ${{ steps.audit.outputs.high-count }}
  has-vulnerabilities:
    description: 'Whether any vulnerabilities were found'
    value: ${{ steps.audit.outputs.has-vulnerabilities }}

runs:
  using: 'composite'
  steps:
    - name: Run security audit
      id: audit
      shell: bash
      run: |
        echo "🔍 Running security audit..."
        
        if bun audit --json > audit-results.json 2>&1; then
          echo "✅ No vulnerabilities found"
          echo "critical-count=0" >> $GITHUB_OUTPUT
          echo "high-count=0" >> $GITHUB_OUTPUT
          echo "has-vulnerabilities=false" >> $GITHUB_OUTPUT
        else
          # Count vulnerabilities by severity
          CRITICAL_COUNT=$(jq -r '[.advisories[] | select(.severity == "critical")] | length' audit-results.json 2>/dev/null || echo "0")
          HIGH_COUNT=$(jq -r '[.advisories[] | select(.severity == "high")] | length' audit-results.json 2>/dev/null || echo "0")
          TOTAL_COUNT=$(jq -r '[.advisories[]] | length' audit-results.json 2>/dev/null || echo "0")
          
          echo "critical-count=$CRITICAL_COUNT" >> $GITHUB_OUTPUT
          echo "high-count=$HIGH_COUNT" >> $GITHUB_OUTPUT
          echo "has-vulnerabilities=$([ "$TOTAL_COUNT" -gt 0 ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
          
          echo "📊 Vulnerability Summary:"
          echo "  - Critical: $CRITICAL_COUNT"
          echo "  - High: $HIGH_COUNT"
          echo "  - Total: $TOTAL_COUNT"
          
          # Fail if configured to do so
          if [[ "${{ inputs.fail-on-critical }}" == "true" && "$CRITICAL_COUNT" -gt 0 ]]; then
            echo "❌ Critical vulnerabilities found - failing audit"
            exit 1
          fi
          
          if [[ "${{ inputs.fail-on-high }}" == "true" && "$HIGH_COUNT" -gt 0 ]]; then
            echo "❌ High severity vulnerabilities found - failing audit"
            exit 1
          fi
        fi

    - name: Upload audit results
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-${{ github.run_id }}
        path: audit-results.json
        retention-days: 30
      continue-on-error: true
