# Dependency Review Configuration
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review

# Fail the action if vulnerabilities with the given severity or higher are found
fail-on-severity: 'moderate'

# Fail the action if vulnerabilities with the given CVSS score or higher are found
fail-on-scopes: 
  - 'runtime'
  - 'development'

# Allow specific licenses
allow-licenses: 
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-3-Clause'
  - 'BSD-2-Clause'
  - 'ISC'
  - '0BSD'
  - 'CC0-1.0'

# Deny specific licenses
deny-licenses:
  - 'GPL-3.0'
  - 'LGPL-3.0'
  - 'AGPL-3.0'
  - 'GPL-2.0'
  - 'LGPL-2.1'

# Allow specific packages even if they have vulnerabilities
allow-dependencies-licenses: 
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-3-Clause'
  - 'ISC'

# Configuration for vulnerability checks
vulnerability-check: true
license-check: true

# Custom comment template for PR summary
comment-summary-in-pr: true

# Additional configuration
retry-on-snapshot-warnings: true
retry-on-snapshot-warnings-timeout: 120

# Package patterns to always allow (trusted sources)
allow-ghsas: []

# Package patterns to always deny
deny-packages: []
