# Dependency review configuration
fail-on-severity: high
vulnerability-check: true
license-check: false

# Allow specific licenses (add as needed)
# allow-licenses:
#   - MIT
#   - Apache-2.0
#   - BSD-2-Clause
#   - BSD-3-Clause
