name: Pre-Dependabot Bun Update

on:
  schedule:
    # Run before Dependabot's weekly Monday 09:00 UTC schedule
    - cron: "0 8 * * 1"
  workflow_dispatch:

concurrency:
  group: bun-update
  cancel-in-progress: false

env:
  FORCE_COLOR: 1

jobs:
  bun-update:
    name: Run bun update
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run bun update
        run: bun update

      - name: Create PR if changes
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(deps): bun update"
          title: "chore(deps): bun update"
          body: |
            Automated `bun update` run prior to Dependabot. This helps reduce churn and keep the lockfile fresh.
          branch: chore/bun-update
          labels: dependencies, dependabot
          delete-branch: true
          signoff: false

      - name: Output PR info
        if: steps.create-pr.outputs.pull-request-number
        run: |
          echo "Created/updated PR #${{ steps.create-pr.outputs.pull-request-number }}"

