name: Push DB schema to Neon (prod)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-db:
    if: ${{ secrets.DATABASE_URL_PROD != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Push schema to Neon (prod)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
        run: bun run db:push
