name: Lighthouse CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "**/*.md"

permissions:
  contents: read

concurrency:
  group: lhci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lhci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        id: setup-bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.x"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: lighthouserc.json
          uploadArtifacts: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}


